[GateServer]
port = 8080

[VerifyServer]
host = 127.0.0.1
port = 50051

[StatusServer]
host = 127.0.0.1
port = 50052

[Mysql]
host = 192.168.134.128
port = 3307
#host = localhost
#port = 3306
passwd = 123456
user = root
#schema = wechat_docker
schema = user_info

[Redis]
host = localhost
port = 6380
passwd = 123456
