syntax = "proto3";

package message;

service VerifyService {
	rpc getVerifyCode (GetVerifyReq) returns (GetVerifyRes);
}

message GetVerifyReq {
	string email = 1;
}

message GetVerifyRes {
	int32 error = 1;
	string email = 2;
	string code = 3;
}

message GetChatServerReq {
	int32 uid = 1;
}

message GetChatServerRes {
	int32 error = 1;
	string host = 2;
	string port = 3;
	string token = 4;
}

message LoginReq {
	int32 uid = 1;
	string token = 2;
}

message LoginRes {
	int32 error = 1;
	int32 uid = 2;
	string token = 3;
}

service StatusService {
	rpc getChatServer (GetChatServerReq) returns (GetChatServerRes) {

	}
	rpc login (LoginReq) returns (LoginRes);
}
